- settings
- settings/__init__.py
- settings/dev.py
- settings/prod.py
- mainapp
- mainapp/__init__.py
- mainapp/models.py
- mainapp/views.py
- mainapp/templates
- mainapp/templates/mainapp
- mainapp/templates/mainapp/base.html
- mainapp/templates/mainapp/index.html
- authapp
- authapp/__init__.py
- authapp/models.py
- authapp/views.py
- authapp/templates
- authapp/templates/authapp
- authapp/templates/authapp/base.html
- authapp/templates/authapp/index.html
